// src/kg/entity_extractor.rs
//! Bridge between parser symbols and knowledge graph entities.

use crate::kg::client::KgClient;
use crate::kg::model::{CodeEntity, ComponentType, EntityMetadata, EntityType, Visibility};
use crate::parser::{ASTNode, Symbol};
use crate::{Error, Result};
use chrono;
use std::collections::HashMap;
use std::path::Path;

/// Extracts knowledge graph entities from parsed symbols
pub struct EntityExtractor {
    /// Repository ID for the current indexing session
    repository_id: i32,
    /// Cache of components by path to avoid duplicate lookups
    component_cache: HashMap<String, i32>,
}

impl EntityExtractor {
    /// Create a new entity extractor for the given repository
    pub fn new(repository_id: i32) -> Self {
        Self {
            repository_id,
            component_cache: HashMap::new(),
        }
    }

    /// Update the repository ID for this extractor
    ///
    /// This is useful when the repository ID is not known at construction time.
    pub fn set_repository_id(&mut self, repository_id: i32) {
        self.repository_id = repository_id;
        // Clear component cache when repository ID changes
        self.component_cache.clear();
    }

    /// Convert parser symbols to knowledge graph entities
    ///
    /// # Arguments
    /// * `symbols` - Symbols extracted by the parser
    /// * `file_path` - Path to the source file
    /// * `language` - Programming language
    /// * `kg_client` - Knowledge graph client for component operations
    ///
    /// # Returns
    /// Vector of code entities ready for insertion into knowledge graph
    pub async fn symbols_to_entities(
        &mut self,
        symbols: Vec<Symbol>,
        file_path: &str,
        language: &str,
        kg_client: &dyn KgClient,
    ) -> Result<Vec<CodeEntity>> {
        let mut entities = Vec::new();

        // Get or create component for this file
        let component_id = self.get_or_create_component(file_path, kg_client).await?;

        for symbol in symbols {
            if let Some(entity) =
                self.symbol_to_entity(symbol, component_id, file_path, language)?
            {
                entities.push(entity);
            }
        }

        Ok(entities)
    }

    /// Convert a single parser symbol to a knowledge graph entity
    fn symbol_to_entity(
        &self,
        symbol: Symbol,
        component_id: i32,
        file_path: &str,
        language: &str,
    ) -> Result<Option<CodeEntity>> {
        // Map symbol kind to entity type
        let entity_type = self.map_symbol_kind_to_entity_type(&symbol.kind)?;

        // Determine visibility (default to private for now)
        let visibility = self.determine_visibility(&symbol, language);

        // Create metadata
        let metadata = EntityMetadata {
            signature: symbol.signature,
            doc_comment: symbol.docstring,
            language: language.to_string(),
        };

        let entity = CodeEntity {
            id: 0, // Will be set by database
            component_id,
            name: symbol.name,
            entity_type,
            file_path: file_path.to_string(),
            line_start: symbol.start_line as u32,
            line_end: symbol.end_line as u32,
            visibility,
            metadata,
            summary: None, // Will be generated by LLM later
            created_at: chrono::Utc::now(),
            updated_at: chrono::Utc::now(),
        };

        Ok(Some(entity))
    }

    /// Map parser symbol kind to knowledge graph entity type
    fn map_symbol_kind_to_entity_type(&self, symbol_kind: &str) -> Result<EntityType> {
        match symbol_kind {
            "function" => Ok(EntityType::Function),
            "class" => Ok(EntityType::Class),
            "method" => Ok(EntityType::Method),
            "struct" => Ok(EntityType::Struct),
            "enum" => Ok(EntityType::Enum),
            "trait" => Ok(EntityType::Trait),
            "interface" => Ok(EntityType::Interface),
            "constant" => Ok(EntityType::Constant),
            "variable" => Ok(EntityType::Variable),
            _ => Err(Error::Parse(format!(
                "Unsupported symbol kind: {}",
                symbol_kind
            ))),
        }
    }

    /// Determine entity visibility from symbol and language context
    fn determine_visibility(&self, _symbol: &Symbol, _language: &str) -> Visibility {
        // For now, default to private
        // TODO: Implement language-specific visibility detection
        // - Python: underscore prefix, name mangling
        // - Rust: pub keyword
        // - Java: public/private/protected keywords
        // - C++: public/private/protected sections
        Visibility::Private
    }

    /// Get or create component for the given file path
    async fn get_or_create_component(
        &mut self,
        file_path: &str,
        kg_client: &dyn KgClient,
    ) -> Result<i32> {
        // Check cache first
        if let Some(&component_id) = self.component_cache.get(file_path) {
            return Ok(component_id);
        }

        // Determine component path and type from file path
        let (component_path, component_type) = self.extract_component_info(file_path)?;

        // For now, create a new component each time
        // TODO: Implement component lookup and caching
        let component_name = self.extract_component_name(&component_path);
        let component = crate::kg::model::Component {
            id: 0, // Will be set by database
            repository_id: self.repository_id,
            name: component_name,
            path: component_path.clone(),
            component_type,
            summary: None, // Will be generated by LLM later
            created_at: chrono::Utc::now(),
            updated_at: chrono::Utc::now(),
        };

        let component_id = kg_client.create_component(component).await?;

        self.component_cache
            .insert(file_path.to_string(), component_id);
        Ok(component_id)
    }

    /// Extract component path and type from file path
    fn extract_component_info(&self, file_path: &str) -> Result<(String, ComponentType)> {
        let path = Path::new(file_path);

        // Remove file extension to get component path
        let component_path = path
            .with_extension("")
            .to_str()
            .ok_or_else(|| Error::Parse(format!("Invalid path: {}", file_path)))?
            .to_string();

        // Determine component type based on directory structure
        let component_type = if path.parent().is_some_and(|p| {
            p.file_name()
                .is_some_and(|name| name == "src" || name == "lib")
        }) {
            ComponentType::Module
        } else if path.components().count() > 2 {
            ComponentType::Package
        } else {
            ComponentType::Directory
        };

        Ok((component_path, component_type))
    }

    /// Extract component name from component path
    fn extract_component_name(&self, component_path: &str) -> String {
        let path = Path::new(component_path);

        // Use the last directory or file name as component name
        if let Some(name) = path.file_name() {
            name.to_str().unwrap_or("unknown").to_string()
        } else {
            "root".to_string()
        }
    }

    /// Extract relationships between symbols from AST
    ///
    /// Analyzes AST to find function calls, imports, inheritance, etc.
    /// This is a placeholder for future implementation.
    pub async fn extract_relationships(
        &self,
        _ast: &ASTNode,
        _entities: &[CodeEntity],
        _language: &str,
    ) -> Result<Vec<crate::kg::model::RelatedEntity>> {
        // TODO: Implement relationship extraction
        // - Function calls
        // - Import statements
        // - Inheritance relationships
        // - Composition/association
        Ok(Vec::new())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_map_symbol_kind_to_entity_type() {
        let extractor = EntityExtractor::new(1);

        assert_eq!(
            extractor
                .map_symbol_kind_to_entity_type("function")
                .unwrap(),
            EntityType::Function
        );
        assert_eq!(
            extractor.map_symbol_kind_to_entity_type("class").unwrap(),
            EntityType::Class
        );
        assert_eq!(
            extractor.map_symbol_kind_to_entity_type("method").unwrap(),
            EntityType::Method
        );
        assert_eq!(
            extractor.map_symbol_kind_to_entity_type("struct").unwrap(),
            EntityType::Struct
        );
        assert_eq!(
            extractor.map_symbol_kind_to_entity_type("enum").unwrap(),
            EntityType::Enum
        );
        assert_eq!(
            extractor.map_symbol_kind_to_entity_type("trait").unwrap(),
            EntityType::Trait
        );

        assert!(extractor.map_symbol_kind_to_entity_type("unknown").is_err());
    }

    #[test]
    fn test_determine_visibility() {
        let extractor = EntityExtractor::new(1);
        let symbol = Symbol {
            name: "test_function".to_string(),
            kind: "function".to_string(),
            signature: Some("fn test_function()".to_string()),
            docstring: None,
            start_line: 1,
            end_line: 5,
            text: "fn test_function() {}".to_string(),
        };

        // Should default to private for now
        assert_eq!(
            extractor.determine_visibility(&symbol, "rust"),
            Visibility::Private
        );
    }

    #[test]
    fn test_extract_component_info() {
        let extractor = EntityExtractor::new(1);

        // Test src/ directory (should be Module)
        let (path, comp_type) = extractor.extract_component_info("src/main.rs").unwrap();
        assert_eq!(path, "src/main");
        assert_eq!(comp_type, ComponentType::Module);

        // Test lib/ directory (should be Module)
        let (path, comp_type) = extractor.extract_component_info("lib/utils.rs").unwrap();
        assert_eq!(path, "lib/utils");
        assert_eq!(comp_type, ComponentType::Module);

        // Test deep path (should be Package)
        let (path, comp_type) = extractor
            .extract_component_info("src/utils/helpers.rs")
            .unwrap();
        assert_eq!(path, "src/utils/helpers");
        assert_eq!(comp_type, ComponentType::Package);
    }

    #[test]
    fn test_extract_component_name() {
        let extractor = EntityExtractor::new(1);

        assert_eq!(extractor.extract_component_name("src/main"), "main");
        assert_eq!(extractor.extract_component_name("lib/utils"), "utils");
        assert_eq!(extractor.extract_component_name("helpers"), "helpers");
        assert_eq!(extractor.extract_component_name(""), "root");
    }

    #[test]
    fn test_symbol_to_entity() {
        let extractor = EntityExtractor::new(1);
        let symbol = Symbol {
            name: "test_function".to_string(),
            kind: "function".to_string(),
            signature: Some("fn test_function() -> i32".to_string()),
            docstring: Some("Test function documentation".to_string()),
            start_line: 10,
            end_line: 15,
            text: "fn test_function() -> i32 { 42 }".to_string(),
        };

        let entity = extractor
            .symbol_to_entity(symbol, 1, "src/test.rs", "rust")
            .unwrap()
            .unwrap();

        assert_eq!(entity.name, "test_function");
        assert_eq!(entity.entity_type, EntityType::Function);
        assert_eq!(entity.component_id, 1);
        assert_eq!(entity.file_path, "src/test.rs");
        assert_eq!(entity.line_start, 10);
        assert_eq!(entity.line_end, 15);
        assert_eq!(entity.visibility, Visibility::Private);
        assert_eq!(entity.metadata.language, "rust");
        assert_eq!(
            entity.metadata.signature,
            Some("fn test_function() -> i32".to_string())
        );
        assert_eq!(
            entity.metadata.doc_comment,
            Some("Test function documentation".to_string())
        );
    }
}
